services:
  cb-db:
    container_name: cb-db
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./prisma/db:/var/lib/postgresql/data
    ports:
      - 6432:5432
  cb-app:
    container_name: cb-app
    build:
      context: .
      dockerfile: app.dockerfile
    restart: unless-stopped
    depends_on:
      - cb-db
    ports:
      - 5555:5555
      - 5173:5173
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@cb-db:5432/postgres
